Fix collection was modified error
Cause possible this error
ERROR|Jaeger.Reporters.RemoteReporter|QueueProcessor error ░
System.InvalidOperationException: Collection was modified; enumeration operation may not execute. ░
at System.Collections.Generic.List`1.Enumerator.MoveNextRare() ░
at Jaeger.Reporters.Protocols.JaegerThriftSpanConverter.BuildLogs(IEnumerable`1 logs) ░
at Jaeger.Reporters.Protocols.JaegerThriftSpanConverter.ConvertSpan(Span span) ░
at Jaeger.Senders.ThriftSender.AppendAsync(Span span, CancellationToken cancellationToken) ░
at Jaeger.Reporters.RemoteReporter.ProcessQueueLoop()

Signed-off-by: Dmitriy Grebennikov <dgrebennikov@ozon.ru>